---
- name: Instalação do rport na versão 0.9.12 em desktops linux
  hosts: localhost
  connection: local
  become: true
  vars:
    so_user: 
    repo_url: 
    repo_user: 
    repo_pass: 
  tasks:
    - name: Garantindo instalação de pacotes básicos do linux
      package:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - htop
          - curl
          - wget
          - ncdu
          - tree
          - libgtk2.0-0:i386
          - libqt5webkit5
          - vlc
          - flameshot
    - block:
      - name: Verificando se o RPORT está instalado
        stat:
          path: /usr/local/bin/rport
        register: rport
      - name: Tentando baixar o RPORT
        get_url:
          url: 'https://{{ repo_url }}/rport.sh'
          dest: '/home/{{ so_user }}/Downloads/rport.sh'
          username: '{{ repo_user }}'
          password: '{{ repo_pass }}'          
        when: not rport.stat.exists
      - name: Tentando baixar dependencias do RPORT
        get_url:
          url: 'https://{{ repo_url }}/rport_0.9.12_linux_x86_64.tar.gz'
          dest: '/tmp/rport-install/rport.tar.gz'
          username: '{{ repo_user }}'
          password: '{{ repo_pass }}'
        when: not rport.stat.exists
       - name: Tentando baixar tacoscript para o RPORT
        get_url:
          url: 'https://{{ repo_url }}/tacoscript_0.3.0_linux_x86_64.tar.gz'
          dest: '/tmp/tacoscript.tar.gz'
          username: '{{ repo_user }}'
          password: '{{ repo_pass }}'
        when: not rport.stat.exists
      - name: Tentando instalar o RPORT
        shell: 'sh /home/{{ so_user }}/Downloads/rport.sh -x -s -r -b -i'
        args:
          warn: false
        when: not rport.stat.exists
    - block:
      - name: Garantindo configuração de memória swap
        lineinfile:
          path: /etc/sysctl.conf
          line: "vm.swappiness = 0"
          state: present
